name: walls_art_app
description: Premium HD & 4K wallpapers for your device
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Networking
  dio: ^5.7.0

  # Data Classes
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.3

  # Image Loading & Caching
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Fonts
  google_fonts: ^8.0.1

  # Ads
  #google_mobile_ads: ^5.2.0

  # Utilities
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0

  # UI Helpers
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Routing
  go_router: ^17.1.0

  # Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7


flutter_native_splash:
  color: "#0C1017"       # Solid background color
  image: null            # No logo
  fullscreen: true       # Hides status bar on Android
  android: true
  ios: true
  web: true             # optional, set false if you don't want splash on web

    # ================== ANDROID 12+ ===================
  android_12:
    color: "#0C1017"               # Background color for Android 12+
    image: null                     # No logo
    icon_background_color: "#0C1017" # Background behind icon (even if system tries to show it)


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"   # the 512x512 PNG
  adaptive_icon_background: "#0C1017"
  adaptive_icon_foreground: "assets/icons/app_icon.png" # transparent logo

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

